# Generated by Django 3.2.3 on 2022-12-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Push_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(max_length=250)),
                ('image', models.ImageField(blank=True, default='https://x-eats.com/static/images/logo/logo%20-new.png', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Push Notifications',
            },
        ),
    ]
