# Generated by Django 3.2.3 on 2022-12-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0002_push_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='push_notification',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
