# Generated by Django 3.2.3 on 2022-12-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0003_push_notification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=2500)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Tokens',
            },
        ),
        migrations.RemoveField(
            model_name='push_notification',
            name='token',
        ),
    ]
