# Generated by Django 3.2.3 on 2022-12-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0004_auto_20221219_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_token',
            name='token',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
