# Generated by Django 3.2.3 on 2022-12-25 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryslug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Categories'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='Mobile_Poster'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.category'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
