# Generated by Django 3.2.3 on 2022-10-31 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=250, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=250, null=True)),
                ('categoryslug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='Categories')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, unique=True)),
                ('background_image', models.ImageField(blank=True, upload_to='codeCategories')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('ArabicName', models.CharField(blank=True, max_length=250, null=True)),
                ('productslug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(default=0)),
                ('boughtPrice', models.FloatField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(default=True)),
                ('Most_Popular', models.BooleanField(default=False)),
                ('New_Products', models.BooleanField(default=False)),
                ('Best_Offer', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=250, unique=True)),
                ('restaurant_slug', models.SlugField(unique=True)),
                ('address', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='Restaurant')),
                ('delivery_fees', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_order', models.TimeField()),
                ('end_order', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.RemoveField(
            model_name='codes',
            name='category',
        ),
        migrations.AddField(
            model_name='promocode',
            name='avaliable_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Code_Categories',
        ),
        migrations.DeleteModel(
            name='Codes',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='product',
            name='Restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.restaurant'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='Restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.restaurant'),
        ),
    ]
