# Generated by Django 3.2.3 on 2022-10-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0002_auto_20221031_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
