# Generated by Django 3.2.3 on 2022-10-31 16:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0002_auto_20221031_1818'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart_and_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, null=True)),
                ('delivery_fees', models.FloatField(default=0)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'DeliveryFees',
            },
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='shipped',
        ),
        migrations.RemoveField(
            model_name='order',
            name='BromoCode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveryFees',
        ),
        migrations.RemoveField(
            model_name='order',
            name='offerPercentage',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_after_offer',
        ),
        migrations.AddField(
            model_name='cart',
            name='Promo_code_user',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_after_delivery',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='flag',
            field=models.CharField(blank=True, default='Web', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price_after_delivery',
            field=models.FloatField(default=0, verbose_name='After Delivery'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart_and_orders.cart'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart_and_orders.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
