# Generated by Django 3.2.3 on 2022-10-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0003_auto_20221031_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Promo_code_user',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
