# Generated by Django 3.2.3 on 2022-10-31 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0003_alter_restaurant_address'),
        ('cart_and_orders', '0004_alter_cart_promo_code_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='Restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.restaurant'),
        ),
    ]
