# Generated by Django 3.2.3 on 2022-11-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0005_cartitems_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='Order Shift',
            field=models.IntegerField(default=1),
        ),
    ]
