# Generated by Django 3.2.3 on 2022-11-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0006_cartitems_order shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='Order Shift',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
