# Generated by Django 3.2.3 on 2022-11-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_and_orders', '0007_alter_cartitems_order shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='Order Shift',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='order_shift',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
